### PR TITLE
Implemented logging into file

### PR DESCRIPTION
**Pull request by hj1ax**
- Deleted __pycache__
- Implemented save to file

### CODE REVIEW

**Review by Cogno-Marco — APPROVED** [review]
Nothing to say, just a really good implementation. I will expand on this by making that each log is automatically saved to txt without colors, so if you want to implement it yourself that's a nice thing to think about, else I'll make it myself when I have a proper architecture working 🚀

**Comment by hj1ax** [comment]
> 
> 
> Nothing to say, just a really good implementation. I will expand on this by making that each log is automatically saved to txt without colors, so if you want to implement it yourself that's a nice thing to think about, else I'll make it myself when I have a proper architecture working 🚀

i can try to implement that later.

**Comment by Cogno-Marco** [comment]
> i can try to implement that later.

Awesome! I'll leave that to you then.

**Comment by Cogno-Marco** [comment]
All clear for the merge 🚀

**Pull request merged**
